name: umpire-quiz
services:
  reverse-proxy:
    image: bramjanssens/umpire-quiz-reverse-proxy:${PROXY_VERSION}
    ports:
      - "81:80"

  frontend:
    image: bramjanssens/umpire-quiz-front-end:${FRONTEND_VERSION}
    pull_policy: always
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      QUESTION_SERVICE_URL: "${QUESTION_SERVICE_URL}"
      USER_SERVICE_URL: "${USER_SERVICE_URL}"
      IMPORTER_URL: "${IMPORTER_URL}"

  question-service:
    image: bramjanssens/umpire-quiz-question-service:${QUESTION_SERVICE_VERSION}
    pull_policy: always
    healthcheck:
      test: [ "CMD", "curl http://localhost:9080/health/ready" ]
      interval: 10s
      timeout: 10s
      retries: 24
      start_period: 10s
    ports:
      - "${QUESTION_SERVICE_PORT}:9080"
    environment:
      MYSQL_HOSTNAME: "question-service-db"
      MYSQL_PORT: "3306"
      MYSQL_ROOT_PASSWORD: "${QUESTION_SERVICE_DB_PASSWORD}"
      MYSQL_DATABASE: "${QUESTION_SERVICE_DB_NAME}"
      FRONTEND_URL: "${FRONTEND_URL}"
      JWT_SHAREDKEY: "${JWT_SHAREDKEY}"
    depends_on:
      question-service-db:
        condition: service_healthy

  question-service-db:
    image: mysql:${DB_VERSION}
    pull_policy: missing
    healthcheck:
      test: [ "CMD", "mysqladmin ping -h 127.0.0.1 --user=root --password=${QUESTION_SERVICE_DB_PASSWORD}" ]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: "${QUESTION_SERVICE_DB_PASSWORD}"
      MYSQL_DATABASE: "${QUESTION_SERVICE_DB_NAME}"
    volumes:
      - "question-service-db-data:/var/lib/mysql"

  # --- Importer service --- #
  importer-service:
    image: bramjanssens/umpire-quiz-importer-service:${IMPORTER_SERVICE_VERSION}
    pull_policy: always
    ports:
      - "${IMPORTER_SERVICE_PORT}:9080"
    environment:
      MYSQL_HOSTNAME: "question-service-db"
      MYSQL_PORT: "3306"
      MYSQL_ROOT_PASSWORD: "${QUESTION_SERVICE_DB_PASSWORD}"
      MYSQL_DATABASE: "${QUESTION_SERVICE_DB_NAME}"
      FRONTEND_URL: "${FRONTEND_URL}"
      JWT_SHAREDKEY: "${JWT_SHAREDKEY}"
    depends_on:
      question-service-db:
        condition: service_healthy
      question-service:
        condition: service_healthy
  # --- End Importer service --- #

  # --- User service --- #
  user-service:
    image: bramjanssens/umpire-quiz-user-service:${USER_SERVICE_VERSION}
    pull_policy: always
    ports:
      - "${USER_SERVICE_PORT}:9080"
    environment:
      MYSQL_HOSTNAME: "user-service-db"
      MYSQL_PORT: "3306"
      MYSQL_PASSWORD: "${USER_SERVICE_DB_PASSWORD}"
      MYSQL_DATABASE: "${USER_SERVICE_DB_NAME}"
      FRONTEND_URL: "${FRONTEND_URL}"
      JWT_SHAREDKEY: "${JWT_SHAREDKEY}"
    depends_on:
      user-service-db:
        condition: service_healthy

  user-service-db:
    image: mysql:${DB_VERSION}
    pull_policy: missing
    healthcheck:
      test: [ "CMD", "mysqladmin ping -h 127.0.0.1 --user=root --password=${USER_SERVICE_DB_PASSWORD}" ]
      interval: 30s
      start_period: 10s
      timeout: 10s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: "${USER_SERVICE_DB_PASSWORD}"
      MYSQL_DATABASE: "${USER_SERVICE_DB_NAME}"
    volumes:
      - "user-service-db-data:/var/lib/mysql"
  # --- End User service --- #

volumes:
  question-service-db-data:
  user-service-db-data:
