services:
  my-proxy:
    build: .
    ports:
      - "81:80"
    networks:
      - demo
  demo:
    image: nginxdemos/hello
    ports:
      - "3000:80"
    networks:
      - demo

networks:
  demo:
